--1.新增資料表(UserHistorySet)
CREATE TABLE [dbo].[UserHistorySet](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FtisUHId] [int] NULL,
	[Name] [nvarchar](40) NULL,
	[Year] [int] NULL,
 CONSTRAINT [PK_UserHistorySet] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--2.新增資料表(UserHistorySetBid)
CREATE TABLE [dbo].[UserHistorySetBid](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UHSetId] [bigint] NULL,
	[Name] [nvarchar](100) NULL,
 CONSTRAINT [PK_UserHistorySetBid] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
